framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    session:
        name: jobs-session
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax
    esi: true
    fragments: true
    php_errors:
        log: true
